import os
import time

os.system('speak "Now I am angry"')
time.sleep(1)
os.system('anim-play /usr/robokind/etc/gui/anims/AZR25_angry_01.anim.xml')
time.sleep(5)
os.system('speak "Now I am denying"')
time.sleep(1)
os.system('anim-play /usr/robokind/etc/gui/anims/AZR25_denial_01.anim.xml')
time.sleep(5)
os.system('speak "Now I am enraged"')
time.sleep(1)
os.system('anim-play /usr/robokind/etc/gui/anims/AZR25_enraged_01.anim.xml')
time.sleep(5)
os.system('speak "Now I am afraid"')
time.sleep(1)
os.system('anim-play /usr/robokind/etc/gui/anims/AZR25_fear_01.anim.xml')
time.sleep(5)
os.system('speak "Now I am happy"')
time.sleep(1)
os.system('anim-play /usr/robokind/etc/gui/anims/AZR25_happy_01.anim.xml')
time.sleep(5)
os.system('speak "Now I have a panic attack"')
time.sleep(1)
os.system('anim-play /usr/robokind/etc/gui/anims/AZR25_panic_01.anim.xml')
time.sleep(5)
os.system('speak "Now I am sad"')
time.sleep(1)
os.system('anim-play /usr/robokind/etc/gui/anims/AZR25_sad_01.anim.xml')
time.sleep(5)
os.system('speak "Now I am scared"')
time.sleep(1)
os.system('anim-play /usr/robokind/etc/gui/anims/AZR25_scared_02_4000.anim.xml')
time.sleep(5)
os.system('speak "Now I am surprised"')
time.sleep(1)
os.system('anim-play /usr/robokind/etc/gui/anims/AZR25_surprise_01.anim.xml')
time.sleep(5)
os.system('speak "Now I am sleepy, bye bye"')
time.sleep(1.5)
os.system('anim-play /usr/robokind/etc/gui/anims/AZR25_yawn_01.anim.xml')
time.sleep(5)
os.system('anim-play /usr/robokind/etc/gui/anims/AZR25_defaults.anim.xml')
